site_name: My Sample Project Documentation
site_description: Complete documentation for my sample project with enhanced features
site_author: eks-pro
site_url: https://eks-pro.github.io/sample-project/

# Repository
repo_name: sample-project
repo_url: https://github.com/eks-pro/sample-project
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Tutorials:
    - Basic Usage: tutorials/basic.md
    - Advanced Usage: tutorials/advanced.md
    - Best Practices: tutorials/best-practices.md
  - API Reference:
    - Overview: api/overview.md
    - Classes: api/classes.md
    - Functions: api/functions.md
  - Contributing: 
    - Guidelines: contributing/guidelines.md
    - Development Setup: contributing/development.md
  - Changelog: changelog.md
  - FAQ: faq.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      use_pygments: true
      linenums: true
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: datetime
      timezone: UTC
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.13.8/dist/mermaid.min.js

# Extra
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eks-pro
      name: GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eks-pro
      name: Twitter Profile
  version:
    provider: mike
    default: latest

# Copyright
copyright: Copyright &copy; 2025 eks-pro
